[default]

# Options are 'none', 'asset-url', and 'slice'. This option controls creating
# Lua files next to each uploaded asset that can be loaded to get information
# about the underlying asset.
codegen = "slice"

# Defines whether images controlled by this config are allowed to be merged into
# a spritesheet.
#
# Some uses of images, like textures on parts, must be separate images in order
# for UVs and wrapping to work correctly.
can-spritesheet = true