[inputs."dont-pack-these/hello.png"]
hash = "8d934edb7179e560668c1f8545e06133389f177f972ef5f0ddaf4738b9ba6f86"
id = 4597156087
packable = false
codegen = "url-and-slice"

[inputs."pack-these/a.png"]
packable = true
codegen = "url-and-slice"

[inputs."pack-these/b.png"]
packable = true
codegen = "url-and-slice"

[inputs."pack-these/c.png"]
packable = true
codegen = "url-and-slice"

[inputs."pack-these/d.png"]
packable = true
codegen = "url-and-slice"

[inputs."pack-these/e.png"]
packable = true
codegen = "url-and-slice"
